###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    postgres:
      image: postgres:10.0-alpine
      container_name: contract-postgres
      working_dir: /application
      environment:
        - POSTGRES_USER=cagatay
        - POSTGRES_PASSWORD=rootpass
      ports:
        - "8084:5432"
      networks:
        default:
          ipv4_address: 192.168.0.4
      volumes:
        - "./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql"

    webserver:
      image: nginx:alpine
      container_name: contract-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: contract-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: 192.168.0.4/16