name: PHP Composer

on:
  push:
    branches: [ prod ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Create .env
      run: 
        touch .env && 
        echo APP_ENV=prod >> .env  && 
        echo APP_DEBUG=0 >> .env  && 
        echo APP_SECRET=${{ secrets.APP_SECRET }} >> .env  && 
        echo MAILER_URL=${{ secrets.MAILER_URL   }} >> .env  && 
        echo MAIL_FROM_ADDRESS=symfonyshop.tk@yandex.com >> .env  && 
        echo DATABASE_URL=${{ secrets.PROD_DATABASE_URL }} >> .env  && 
        echo APP_NAME=SymfonyShopDev >> .env  && 
        echo MAIN_MAIL_ADDRESS=mustafa.cagatay.yilmaz@gmail.com >> .env

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USER }}
        PORT: ${{ secrets.SSH_PORT }}
        KEY: ${{ secrets.SSH_KEY }}
      with:
        source: "."
        target: "/var/www/symfonyshop"
